subject = "🚨 Endpoint Down Alert: {{ endpoint_name }}"

html = ("<html>"
        "<head>"
        "  <meta charset='UTF-8'>"
        "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "  <style>"
        "    body {"
        "      background-color: #f4f4f4;"
        "      font-family: Arial, sans-serif;"
        "      margin: 0;"
        "      padding: 20px;"
        "    }"
        "    .container {"
        "      max-width: 600px;"
        "      margin: 0 auto;"
        "      background-color: #ffffff;"
        "      padding: 20px;"
        "      border-radius: 8px;"
        "      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"
        "    }"
        "    h1 {"
        "      color: #333333;"
        "      font-size: 24px;"
        "    }"
        "    p {"
        "      font-size: 16px;"
        "      line-height: 1.5;"
        "      color: #666666;"
        "    }"
        "    a {"
        "      color: #1a73e8;"
        "      text-decoration: none;"
        "    }"
        "    a:hover {"
        "      text-decoration: underline;"
        "    }"
        "    .alert-info {"
        "      margin: 20px 0;"
        "      padding: 10px 15px;"
        "      background-color: #ffe8e8;"
        "      border-left: 5px solid #ff4d4d;"
        "      color: #a94442;"
        "    }"
        "    .footer {"
        "      margin-top: 30px;"
        "      font-size: 14px;"
        "      text-align: center;"
        "      color: #999999;"
        "    }"
        "  </style>"
        "</head>"
        "<body>"
        "  <div class='container'>"
        "    <h1>🚨 Endpoint Down Alert</h1>"
        "    <p>Hello {{ user_name }},</p>"
        "    <p>We detected that your monitored endpoint is currently unreachable. Please see the details below:</p>"
        "    <div class='alert-info'>"
        "      <p><strong>🔗 URL:</strong> <a href='{{ endpoint_url }}'>{{ endpoint_url }}</a></p>"
        "      <p><strong>⏱️ Time:</strong> {{ timestamp }}</p>"
        "      <p><strong>📄 Status:</strong> Failed (HTTP {{ status_code }})</p>"
        "    </div>"
        "    <p>We will continue monitoring and notify you of any further changes.</p>"
        "    <p>Regards,<br>PingBot Team</p>"
        "    <div class='footer'>This is an automated alert from PingBot</div>"
        "  </div>"
        "</body>"
        "</html>")
